package installer

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// UserPrompter handles user interaction for confirmation prompts.
type UserPrompter interface {
	ConfirmOverwrite(path string) (bool, error)
}

// InteractivePrompter prompts the user via stdin for confirmation.
type InteractivePrompter struct{}

var _ UserPrompter = (*InteractivePrompter)(nil)

func NewInteractivePrompter() *InteractivePrompter {
	return &InteractivePrompter{}
}

func (p *InteractivePrompter) ConfirmOverwrite(path string) (bool, error) {
	fmt.Printf("File '%s' does not appear to be generated by PIM. Overwrite it? [y/N]: ", path)

	scanner := bufio.NewScanner(os.Stdin)
	if !scanner.Scan() {
		return false, fmt.Errorf("failed to read user input")
	}

	return isYesResponse(scanner.Text()), nil
}

func isYesResponse(response string) bool {
	response = strings.ToLower(strings.TrimSpace(response))

	return response == "y" || response == "yes"
}

// AcceptAllPrompter always allows to overwrite without prompting.
type AcceptAllPrompter struct{}

var _ UserPrompter = (*AcceptAllPrompter)(nil)

func NewAcceptAllPrompter() *AcceptAllPrompter {
	return &AcceptAllPrompter{}
}

func (p *AcceptAllPrompter) ConfirmOverwrite(_ string) (bool, error) {
	return true, nil
}
