package installer

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

type ConcatStrategy struct {
	outputPath string
	outFile    *os.File
}

func NewConcatStrategy(path string) *ConcatStrategy {
	return &ConcatStrategy{
		outputPath: path,
	}
}

func (s *ConcatStrategy) Prepare(force bool) error {
	if !force {
		if _, err := os.Stat(s.outputPath); err == nil {
			// File exists, check frontmatter
			allowOverride, err := canOverride(s.outputPath)
			if err != nil {
				return fmt.Errorf("failed to check frontmatter: %w", err)
			}
			if !allowOverride {
				return fmt.Errorf("user declined to override file '%s'", s.outputPath)
			}
		}
	}

	if err := os.Remove(s.outputPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to delete output file '%s': %w", s.outputPath, err)
	}

	if err := os.MkdirAll(filepath.Dir(s.outputPath), 0755); err != nil {
		return fmt.Errorf("failed to create output directory '%s': %w", filepath.Dir(s.outputPath), err)
	}

	outFile, err := os.Create(s.outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file '%s': %w", s.outputPath, err)
	}

	s.outFile = outFile

	err = AddGeneratedByPimHeader(s.outFile)
	if err != nil {
		return fmt.Errorf("failed to write frontmatter to output file '%s': %w", s.outputPath, err)
	}

	return nil
}

func (s *ConcatStrategy) AddFile(srcPath, _ string) error {
	srcFile, err := os.Open(srcPath)
	if err != nil {
		return fmt.Errorf("failed to open source file '%s': %w", srcPath, err)
	}
	defer srcFile.Close()

	if _, err := io.Copy(s.outFile, srcFile); err != nil {
		return fmt.Errorf("failed to copy file '%s': %w", srcPath, err)
	}

	if _, err := s.outFile.WriteString("\n"); err != nil {
		return fmt.Errorf("failed to write newline to output file '%s': %w", s.outputPath, err)
	}

	return nil
}

func (s *ConcatStrategy) Close() error {
	if s.outFile != nil {
		return s.outFile.Close()
	}
	return nil
}

// canOverride parses frontmatter from a markdown file and checks if it can be overridden.
// It can be overridden if it was generated by PIM (based on generated-by property) or if the user confirms the override.
func canOverride(path string) (bool, error) {
	isGeneratedByPim, err := IsPimGenerated(path)
	if err != nil {
		return false, err
	}
	if isGeneratedByPim {
		return true, nil
	}

	fmt.Printf("File '%s' exists and was not generated by PIM. Override? [y/N]: ", path)

	scanner := bufio.NewScanner(os.Stdin)
	if !scanner.Scan() {
		if err := scanner.Err(); err != nil {
			return false, fmt.Errorf("failed to read user input: %w", err)
		}
		return false, fmt.Errorf("no input received (EOF)")
	}

	response := strings.ToLower(strings.TrimSpace(scanner.Text()))
	return response == "y" || response == "yes", nil
}
